#!/usr/bin/env bash
# manifest_format_test.sh — regression test for the MANIFEST contract (US-25).
#
# Asserts that every field documented in image/MANIFEST.example is actually
# generated by image/build.sh. If a field is dropped from build.sh, this test
# fails — protecting the IT-säk M-04 sign-off from silent rot.
#
# Run locally:  bash image/manifest_format_test.sh
# Or via CI as a step in .github/workflows/ci.yml.
#
# Exit codes:
#   0  all expected fields present
#   1  one or more expected fields missing in build.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_SH="${SCRIPT_DIR}/build.sh"
EXAMPLE="${SCRIPT_DIR}/MANIFEST.example"

[[ -f "${BUILD_SH}" ]] || { echo "FATAL: ${BUILD_SH} missing" >&2; exit 2; }
[[ -f "${EXAMPLE}" ]]  || { echo "FATAL: ${EXAMPLE} missing"  >&2; exit 2; }

# Extract field names from the example: "key=value" lines, ignoring comments
# and blanks. cut on the first '=' so values containing '=' don't break us.
expected_fields=()
while IFS= read -r line; do
    expected_fields+=("$line")
done < <(grep -v '^#' "${EXAMPLE}" | grep -v '^$' | cut -d= -f1)

missing=0
for field in "${expected_fields[@]}"; do
    # Look for "field=" inside the heredoc that build.sh writes to MANIFEST_FILE.
    # The heredoc body is the only place these literal "key=" tokens appear,
    # so a simple grep is robust enough.
    if ! grep -qE "^${field}=" "${BUILD_SH}"; then
        echo "FAIL: ${field} not generated by build.sh"
        missing=$((missing + 1))
    else
        echo "OK:   ${field}"
    fi
done

if [[ ${missing} -gt 0 ]]; then
    echo ""
    echo "MANIFEST regression: ${missing} field(s) missing in build.sh."
    echo "Either restore the field in build.sh or update MANIFEST.example after"
    echo "IT-säk has reviewed and approved the change."
    exit 1
fi

echo ""
echo "All ${#expected_fields[@]} MANIFEST fields are generated by build.sh."
